### ISSUE TITLE
Not Enough Dumbass

### ISSUE THREAD

**Issue by Benjamin8693** [nubbynubbo/Wizard101HardMode#1]

**Comment by nubbynubbo** [comment]
lol

**Comment by Benjamin8693** [comment]
So I'm obsessed with you for communicating for the first time in months? Okay then. What I **AM** obsessed with is searching the term "Wizard101" on Github every other day.

**Comment by nubbynubbo** [comment]
obsession is a clear exaggeration, you missed the point. 

you decided it was a good idea to communicate with me to simply mock me even more than you've already done after months of no communication. that doesn't seem rational. you're free to search 'Wizard101' on github but that doesn't really justify this after months of severed communications.
